export const SET_SELECTED_SHOPPER = 'SET_SELECTED_SHOPPER';

export const SET_CART_FOODS = 'SET_CART_FOODS';

export const DECREASE_COUNT = 'DECREASE_COUNT';

export const EMPTY_CART_FOODS = 'EMPTY_CART_FOODS';
