export const SET_SELECTED_SHOPPER = 'SET_SELECTED_SHOPPER';

export const SET_CART_FOODS = 'SET_CART_FOODS';

export const DECREASE_COUNT = 'DECREASE_COUNT';

export const EMPTY_CART_FOODS = 'EMPTY_CART_FOODS';

export const SET_SELECTED_ENTRIES = 'SET_SELECTED_ENTRIES';

export const SET_LATITUDE = 'SET_LATITUDE';

export const SET_LONGITUDE = 'SET_LONGITUDE';

export const SET_GEOHASH = 'SET_GEOHASH';

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';

export const SET_SHOWFLAGGPS = 'SET_SHOWFLAGGPS';
